version: 3.0

constants:
  baseUrl: http://localhost:3332
  port: 3332
  # please use your own X25519 key, this is only an example
  # you can generate a new key by running `veramo config gen-key` in a terminal
  dbEncryptionKey: 29739248cad1bd1a0fc4d9b75cd4d2990de535baf5caadfdf8d8f86664aa830c
  databaseFile: ./database.sqlite
  methods:
    - keyManagerGetKeyManagementSystems
    - keyManagerCreate
    - keyManagerGet
    - keyManagerDelete
    - keyManagerImport
    - keyManagerEncryptJWE
    - keyManagerDecryptJWE
    - keyManagerSign
    - keyManagerSharedSecret
    - keyManagerSignJWT
    - keyManagerSignEthTX
    - didManagerGetProviders
    - didManagerFind
    - didManagerGet
    - didManagerCreate
    - didManagerGetOrCreate
    - didManagerImport
    - didManagerDelete
    - didManagerAddKey
    - didManagerRemoveKey
    - didManagerAddService
    - didManagerRemoveService
    - resolveDid
    - getDIDComponentById
    - discoverDid
    - dataStoreGetMessage
    - dataStoreSaveMessage
    - dataStoreGetVerifiableCredential
    - dataStoreSaveVerifiableCredential
    - dataStoreGetVerifiablePresentation
    - dataStoreSaveVerifiablePresentation
    - dataStoreORMGetIdentifiers
    - dataStoreORMGetIdentifiersCount
    - dataStoreORMGetMessages
    - dataStoreORMGetMessagesCount
    - dataStoreORMGetVerifiableCredentialsByClaims
    - dataStoreORMGetVerifiableCredentialsByClaimsCount
    - dataStoreORMGetVerifiableCredentials
    - dataStoreORMGetVerifiableCredentialsCount
    - dataStoreORMGetVerifiablePresentations
    - dataStoreORMGetVerifiablePresentationsCount
    - handleMessage
    - packDIDCommMessage
    - unpackDIDCommMessage
    - sendDIDCommMessage
    - sendMessageDIDCommAlpha1
    - createVerifiableCredential
    - createVerifiablePresentation
    - verifyCredential
    - verifyPresentation
    - createSelectiveDisclosureRequest
    - getVerifiableCredentialsForSdr
    - validatePresentationAgainstSdr

# Data base
dbConnection:
  $require: typeorm?t=function#createConnection
  $args:
    - type: sqlite
      database:
        $ref: /constants/databaseFile
      synchronize: false
      migrationsRun: true
      migrations:
        $require: '@sphereon/data-store?t=object#migrations'
      logging: false
      entities:
        $require: '@sphereon/data-store?t=object#Entities'

# Server configuration
server:
  baseUrl:
    $ref: /constants/baseUrl
  port:
    $ref: /constants/port
  use:
    # CORS
    - - $require: 'cors'

    # Add agent to the request object
    - - $require: '@sphereon/remote-server?t=function#RequestWithAgentRouter'
        $args:
          - agent:
              $ref: /agent

    # DID Documents
    - - $require: '@sphereon/remote-server?t=function#WebDidDocRouter'

    # API base path
    - - /messaging
      - $require: '@sphereon/remote-server?t=function#MessagingRouter'
        $args:
          - metaData:
              type: DIDComm
              value: https

    # API base path
    - - /agent
      - $require: '@sphereon/remote-server?t=function#apiKeyAuth'
        $args:
          - apiKey: test123
      - $require: '@sphereon/remote-server?t=function#AgentRouter'
        $args:
          - exposedMethods:
              $ref: /constants/methods

    # Open API schema
    - - /open-api.json
      - $require: '@sphereon/remote-server?t=function#ApiSchemaRouter'
        $args:
          - basePath: :3332/agent
            securityScheme: bearer
            apiName: Agent
            apiVersion: '1.0.0'
            exposedMethods:
              $ref: /constants/methods

    # Swagger docs
    - - /api-docs
      - $require: swagger-ui-express?t=object#serve
      - $require: swagger-ui-express?t=function#setup
        $args:
          - null
          - swaggerOptions:
              url: '/open-api.json'

  # Execute during server initialization
  init:
    - $require: '@sphereon/remote-server?t=function#createDefaultDid'
      $args:
        - agent:
            $ref: /agent
          baseUrl:
            $ref: /constants/baseUrl
          messagingServiceEndpoint: /messaging

# Message handler plugin
messageHandler:
  $require: '@sphereon/message-handler#MessageHandler'
  $args:
    - messageHandlers:
        - $require: '@sphereon/did-comm#DIDCommMessageHandler'
        - $require: '@sphereon/did-jwt#JwtMessageHandler'
        - $require: '@sphereon/credential-w3c#W3cMessageHandler'
        - $require: '@sphereon/selective-disclosure#SdrMessageHandler'

# DID resolvers
didResolver:
  $require: '@sphereon/did-resolver#DIDResolverPlugin'
  $args:
    - resolver:
        $require: did-resolver#Resolver
        $args:
          - ethr:
              $ref: /ethr-did-resolver
            web:
              $ref: /web-did-resolver
            key:
              $ref: /did-key-resolver
            elem:
              $ref: /universal-resolver
            io:
              $ref: /universal-resolver
            ion:
              $ref: /universal-resolver
            sov:
              $ref: /universal-resolver

ethr-did-resolver:
  $require: ethr-did-resolver?t=function&p=/ethr#getResolver
  $args:
    - infuraProjectId: 3586660d179141e3801c3895de1c2eba

web-did-resolver:
  $require: web-did-resolver?t=function&p=/web#getResolver

universal-resolver:
  $require: '@sphereon/did-resolver#UniversalResolver'
  $args:
    - url: https://dev.uniresolver.io/1.0/identifiers/

did-key-resolver:
  $require: '@sphereon/did-provider-key?t=function&p=/key#getDidKeyResolver'

# Key Manager
keyManager:
  $require: '@sphereon/key-manager#KeyManager'
  $args:
    - store:
        $require: '@sphereon/data-store#KeyStore'
        $args:
          - $ref: /dbConnection
      kms:
        local:
          $require: '@sphereon/kms-local#KeyManagementSystem'
          $args:
            - $require: '@sphereon/data-store#PrivateKeyStore'
              $args:
                - $ref: /dbConnection
                - $require: '@sphereon/kms-local#SecretBox'
                  $args:
                    - $ref: /constants/dbEncryptionKey

# DID Manager
didManager:
  $require: '@sphereon/did-manager#DIDManager'
  $args:
    - store:
        $require: '@sphereon/data-store#DIDStore'
        $args:
          - $ref: /dbConnection
      defaultProvider: did:ethr:rinkeby
      providers:
        did:ethr:
          $require: '@sphereon/did-provider-ethr#EthrDIDProvider'
          $args:
            - defaultKms: local
              network: mainnet
              rpcUrl: https://mainnet.infura.io/v3/3586660d179141e3801c3895de1c2eba
              gas: 1000001
              ttl: 31104001
        did:ethr:rinkeby:
          $require: '@sphereon/did-provider-ethr#EthrDIDProvider'
          $args:
            - defaultKms: local
              network: rinkeby
              rpcUrl: https://rinkeby.infura.io/v3/3586660d179141e3801c3895de1c2eba
              gas: 1000001
              ttl: 31104001
        did:ethr:ropsten:
          $require: '@sphereon/did-provider-ethr#EthrDIDProvider'
          $args:
            - defaultKms: local
              network: ropsten
              rpcUrl: https://ropsten.infura.io/v3/3586660d179141e3801c3895de1c2eba
              gas: 1000001
              ttl: 31104001
        did:ethr:kovan:
          $require: '@sphereon/did-provider-ethr#EthrDIDProvider'
          $args:
            - defaultKms: local
              network: kovan
              rpcUrl: https://kovan.infura.io/v3/3586660d179141e3801c3895de1c2eba
              gas: 1000001
              ttl: 31104001
        did:ethr:goerli:
          $require: '@sphereon/did-provider-ethr#EthrDIDProvider'
          $args:
            - defaultKms: local
              network: goerli
              rpcUrl: https://goerli.infura.io/v3/3586660d179141e3801c3895de1c2eba
              gas: 1000001
              ttl: 31104001
        did:web:
          $require: '@sphereon/did-provider-web#WebDIDProvider'
          $args:
            - defaultKms: local
        did:key:
          $require: '@sphereon/did-provider-key#KeyDIDProvider'
          $args:
            - defaultKms: local

didDiscovery:
  $require: '@sphereon/did-discovery#DIDDiscovery'
  $args:
    - providers:
        - $require: '@sphereon/did-manager#AliasDiscoveryProvider'
        - $require: '@sphereon/data-store#ProfileDiscoveryProvider'

# W3C credentialPlugin
credentialIssuerLD:
  $require: '@sphereon/credential-ld#CredentialIssuerLD'
  $args:
    - suites:
        - $require: '@sphereon/credential-ld#VeramoEd25519Signature2018'
        - $require: '@sphereon/credential-ld#VeramoEcdsaSecp256k1RecoverySignature2020'
      contextMaps:
        # The LdDefaultContext is a "catch-all" for now.
        - $require: '@sphereon/credential-ld?t=object#LdDefaultContexts'
        - $require: '@transmute/credentials-context?t=object#contexts'
        #  others should be included here

# Agent
agent:
  $require: '@sphereon/core#Agent'
  $args:
    - schemaValidation: false
      plugins:
        - $ref: /keyManager
        - $ref: /didManager
        - $ref: /didResolver
        - $ref: /didDiscovery
        - $ref: /messageHandler
        - $require: '@sphereon/did-comm#DIDComm'
        - $require: '@sphereon/credential-w3c#CredentialIssuer'
        - $ref: /credentialIssuerLD
        - $require: '@sphereon/selective-disclosure#SelectiveDisclosure'
        - $require: '@sphereon/data-store#DataStore'
          $args:
            - $ref: /dbConnection
        - $require: '@sphereon/data-store#DataStoreORM'
          $args:
            - $ref: /dbConnection
